### ISSUE TITLE
Pre-train on different Dataset than C4

### ISSUE THREAD

**Issue by nikifori** [PiotrNawrot/nanoT5#27]
Is there any option, to pre-train T5-based models on different dataset than C4 in a self-supervised manner?

**Comment by PiotrNawrot** [comment]
@nikifori 

Please accept my apologies for the late reply. I've been very busy lately because of the ICML submission.

To answer your question: Take a look on : https://github.com/PiotrNawrot/nanoT5/issues/11 and  https://github.com/PiotrNawrot/nanoT5/issues/21 

Training on a different dataset seems like a common question so I'll try to add some more information about it to the README.

I'm closing this Issue for now, please feel free to re-open if you have any other questions.
