### ISSUE TITLE
Pre-trained nanoT5 model on C4 corpus

### ISSUE THREAD

**Issue by SungHo3268** [PiotrNawrot/nanoT5#6]
Hi Piotr,

Thank you for your great work on the nanoT5 repository.
I'm going to try to pre-train the T5-base variant model on C4 corpus by using V100 gpu and then I'll evaluate the model on GLUE tasks. I'm referring to your repo nanoT5 and it is very very helpful to me. Thanks a lot, again.
Before I pre-train the model myself, to save the time, I ask to you if there is any pre-trained model you can share for.

Best regard, 
SungHo

**Comment by iSevenDays** [comment]
Hi @SungHo3268 please try my checkpoint https://drive.google.com/drive/folders/1-VQ2yTqxIYgsX8Bq7255ww931Qf32DVY?usp=sharing and tell me how it works. I used C4 + Pile for about 40 hours of V100, but I'm not satisfied with the results. 
Note that I continued training and the last 10-15 hours are not shown on the graph because I had used all free graph points for free version of the neptune logger.
<img width="1121" alt="grafik" src="https://user-images.githubusercontent.com/3992716/231898632-2af84a94-6557-413c-a221-8b34ba60ee4f.png">
<img width="576" alt="grafik" src="https://user-images.githubusercontent.com/3992716/231898651-e7d29c77-0495-48e5-925d-656d9fe5ecf6.png">

**Comment by PiotrNawrot** [comment]
Hi @SungHo3268,
Sorry for the late answer, but I was on extended Easter holidays. I'll upload the model weights for the default config later today.

@iSevenDays 
Firstly, I think you can have full version of neptune without further limitations if you make your project public. Secondly, what are the results you got after 40h on C4+Pile? Have you tried fine-tuning such a model on SNI? What was the config you've used for pre-training? 40h is how many steps on your hardware? I've also wanted to try pre-training on The Pile as it might be more efficient than solely C4. Maybe we could find out the issue behind non-satisfactory results together. Let me know!

**Comment by PiotrNawrot** [comment]
@SungHo3268 

Sorry for the slight delay, you can get the model weights after pre-training [here](https://huggingface.co/pnawrot/nanoT5-base).

**Comment by SungHo3268** [comment]
@PiotrNawrot 

Thank you for your reply and provision.
I'm going to evaluate your model on GLUE tasks. Also, I pre-trained our own nanoT5 model by using your pre-training code, so I'll let you know if it is different with yours. Thanks a lot.

**Comment by PiotrNawrot** [comment]
@SungHo3268 Sure, no worries.

I don't know how you're planning to evaluate the T5 which is seq-to-seq model on GLUE which mostly consist of classification tasks. AFAIK encoder-style like BERT are more suitable. But you can try Crossfit challange if you heard about it - they reformulate the classification tasks into seq-to-seq.
