### ISSUE TITLE
Why isn't the lr warm up from 0?

### ISSUE THREAD

**Issue by jzhang38** [PiotrNawrot/nanoT5#9]
Dear authors:

https://github.com/PiotrNawrot/nanoT5/blob/5a66107acc73617ab628988d90ea86172cc282fc/nanoT5/utils/model_utils.py#L259

It appears that you have configured the learning rate to warm up halfway through the process. Are there any specific reasons for this decision?

**Comment by PiotrNawrot** [comment]
Hey,

No particular reason, we've run less than 10 experiments in total to observe model's behaviour w.r.t. to the LR schedule.

Model starts from really bad spot in a loss space after random initialisation and larger LR at the beginning was beneficial for the quicker convergence, so we included it in the final recipe. 

IIRC some warmup was needed, but starting from 1e-2 was better than starting from 0. 

Moreover, as we wrote in the README this schedule combined with Adam performs the best (Adafactor underperformed due to instabilities).

Hope that clarifies!
